name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update root dependencies
        run: |
          npm update
          npm audit fix --audit-level=moderate || true

      - name: Update test-app dependencies
        run: |
          cd test-app
          npm update
          npm audit fix --audit-level=moderate || true

      - name: Update Playwright
        run: |
          npm install @playwright/test@latest
          npx playwright install

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet package*.json test-app/package*.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Run tests after updates
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          npm ci
          cd test-app && npm ci
          npx playwright install --with-deps
          
          # Start test server
          cd test-app && npm start &
          sleep 5
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:3000/health
          
          # Run API tests only (safer for automated updates)
          npm run test:api
        env:
          CI: true
          HEADLESS: true

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: update dependencies
            
            - Updated npm packages to latest versions
            - Fixed moderate security vulnerabilities
            - Updated Playwright to latest version
          title: 'chore: Weekly dependency updates'
          body: |
            ## Dependency Updates
            
            This PR contains automated dependency updates:
            
            - 📦 Updated npm packages to latest versions
            - 🔒 Fixed moderate security vulnerabilities  
            - 🎭 Updated Playwright to latest version
            - ✅ API tests passed after updates
            
            ### Changes
            - Root package dependencies updated
            - Test app dependencies updated
            - Playwright version updated
            
            ### Verification
            - [x] API tests pass
            - [x] No critical vulnerabilities
            - [x] Dependencies resolve correctly
            
            **Note**: Please review and run full test suite before merging.
          branch: dependency-updates/automated
          delete-branch: true
          draft: false

  update-playwright:
    name: Update Playwright Browsers
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd test-app && npm ci

      - name: Update Playwright browsers
        run: |
          npx playwright install --with-deps
          
      - name: Test updated browsers
        run: |
          cd test-app && npm start &
          sleep 5
          curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:3000/health
          
          # Run quick smoke tests
          npm test src/tests/api/ -- --grep "should respond to health check"
        env:
          CI: true
          HEADLESS: true

      - name: Update Dockerfile Playwright version
        run: |
          # Get current Playwright version
          PLAYWRIGHT_VERSION=$(npm list @playwright/test --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')
          
          # Update Dockerfile
          sed -i "s/playwright:v[0-9.]*/playwright:v${PLAYWRIGHT_VERSION}/" Dockerfile
          
      - name: Create Pull Request for Playwright update
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: update Playwright browsers and Docker image
            
            - Updated Playwright browsers to latest versions
            - Updated Dockerfile to use latest Playwright image
            - Verified browsers work with existing tests
          title: 'chore: Update Playwright browsers'
          body: |
            ## Playwright Browser Update
            
            This PR updates Playwright browsers and Docker configuration:
            
            - 🎭 Updated to latest Playwright browser versions
            - 🐳 Updated Dockerfile to use matching Playwright image
            - ✅ Verified compatibility with existing tests
            
            ### Changes
            - Playwright browsers updated via `npx playwright install`
            - Dockerfile updated to use latest Playwright base image
            - Smoke tests passed
            
            **Note**: Full test suite should be run before merging.
          branch: playwright-update/automated
          delete-branch: true
          draft: false